### PR TITLE
Fixed compound literals not working as normal expressions

### LINKED ISSUE #21: Compound literals do not work
[Compound literals](https://en.cppreference.com/w/c/language/compound_literal) do not seem to work.

Test preprocessed C file:
```c
# 1 "test.c"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "test.c"
typedef struct
{
    int value;
} test_t;

void test(test_t* myStruct)
{
    *myStruct = (test_t) {.value = 1};
}
```

Error:
```
SyntaxError {
    source: --- see above ---,
    line: 12,
    column: 26,
    offset: 173,
    expected: {
        "<",
        "!=",
        "*=",
        "%=",
        "&",
        "==",
        ">",
        "<<",
        "&&",
        ">>",
        "u8",
        "[",
        "~",
        ">=",
        "*",
        "/",
        "++",
        "->",
        "--",
        "+",
        "<<=",
        ";",
        "?",
        "|=",
        "[_a-zA-Z]",
        ">>=",
        "[uUL]",
        "^=",
        ",",
        ".",
        "!",
        "||",
        "(",
        "-=",
        "\"",
        "/=",
        "<=",
        "^",
        "%",
        "=",
        "+=",
        "&=",
        "|",
        "-",
    },
}
```

### PR DESCRIPTION
**Pull request by robbym**
Fixes #21

### CODE REVIEW

**Comment by vickenty** [comment]
Thanks! The fix looks good, although I'm not sure about moving compound literal to primary expressions. Is it necessary? If possible, I'd prefer to keep the grammar close to the standard.

**Comment by robbym** [comment]
It's not necessary, I just thought that's where it would go if it was a primary expression. I'll take a look at the standard.

**Comment by robbym** [comment]
Apparently that was unnecessary! All that was needed was the conversion to `initializer_list_item`.

**Comment by vickenty** [comment]
Great job, thanks!

**Pull request merged**
